# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: microsyntenysearch.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='microsyntenysearch.proto',
  package='microsyntenysearch',
  syntax='proto3',
  serialized_options=b'\n\032lis.gcv.microsyntenysearchB\027MicroSyntenySearchProtoP\001\242\002\002GS',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18microsyntenysearch.proto\x12\x12microsyntenysearch\"E\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x03(\t\x12\x0f\n\x07matched\x18\x02 \x01(\x02\x12\x14\n\x0cintermediate\x18\x03 \x01(\x02\"8\n\x0bSearchReply\x12)\n\x06tracks\x18\x01 \x03(\x0b\x32\x19.microsyntenysearch.Track\"V\n\x05Track\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05genus\x18\x02 \x01(\t\x12\x0f\n\x07species\x18\x03 \x01(\t\x12\r\n\x05genes\x18\x04 \x03(\t\x12\x10\n\x08\x66\x61milies\x18\x05 \x03(\t2d\n\x12MicroSyntenySearch\x12N\n\x06Search\x12!.microsyntenysearch.SearchRequest\x1a\x1f.microsyntenysearch.SearchReply\"\x00\x42<\n\x1alis.gcv.microsyntenysearchB\x17MicroSyntenySearchProtoP\x01\xa2\x02\x02GSb\x06proto3'
)




_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='microsyntenysearch.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='microsyntenysearch.SearchRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='matched', full_name='microsyntenysearch.SearchRequest.matched', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intermediate', full_name='microsyntenysearch.SearchRequest.intermediate', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=117,
)


_SEARCHREPLY = _descriptor.Descriptor(
  name='SearchReply',
  full_name='microsyntenysearch.SearchReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tracks', full_name='microsyntenysearch.SearchReply.tracks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=175,
)


_TRACK = _descriptor.Descriptor(
  name='Track',
  full_name='microsyntenysearch.Track',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='microsyntenysearch.Track.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='genus', full_name='microsyntenysearch.Track.genus', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='species', full_name='microsyntenysearch.Track.species', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='genes', full_name='microsyntenysearch.Track.genes', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='families', full_name='microsyntenysearch.Track.families', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=263,
)

_SEARCHREPLY.fields_by_name['tracks'].message_type = _TRACK
DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['SearchReply'] = _SEARCHREPLY
DESCRIPTOR.message_types_by_name['Track'] = _TRACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'microsyntenysearch_pb2'
  # @@protoc_insertion_point(class_scope:microsyntenysearch.SearchRequest)
  })
_sym_db.RegisterMessage(SearchRequest)

SearchReply = _reflection.GeneratedProtocolMessageType('SearchReply', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREPLY,
  '__module__' : 'microsyntenysearch_pb2'
  # @@protoc_insertion_point(class_scope:microsyntenysearch.SearchReply)
  })
_sym_db.RegisterMessage(SearchReply)

Track = _reflection.GeneratedProtocolMessageType('Track', (_message.Message,), {
  'DESCRIPTOR' : _TRACK,
  '__module__' : 'microsyntenysearch_pb2'
  # @@protoc_insertion_point(class_scope:microsyntenysearch.Track)
  })
_sym_db.RegisterMessage(Track)


DESCRIPTOR._options = None

_MICROSYNTENYSEARCH = _descriptor.ServiceDescriptor(
  name='MicroSyntenySearch',
  full_name='microsyntenysearch.MicroSyntenySearch',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=265,
  serialized_end=365,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='microsyntenysearch.MicroSyntenySearch.Search',
    index=0,
    containing_service=None,
    input_type=_SEARCHREQUEST,
    output_type=_SEARCHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MICROSYNTENYSEARCH)

DESCRIPTOR.services_by_name['MicroSyntenySearch'] = _MICROSYNTENYSEARCH

# @@protoc_insertion_point(module_scope)
