# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from services import microsyntenysearch_pb2 as services_dot_microsyntenysearch__pb2


class MicroSyntenySearchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/gcv.services.MicroSyntenySearch/Search',
                request_serializer=services_dot_microsyntenysearch__pb2.MicroSyntenySearchRequest.SerializeToString,
                response_deserializer=services_dot_microsyntenysearch__pb2.MicroSyntenySearchReply.FromString,
                )


class MicroSyntenySearchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MicroSyntenySearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=services_dot_microsyntenysearch__pb2.MicroSyntenySearchRequest.FromString,
                    response_serializer=services_dot_microsyntenysearch__pb2.MicroSyntenySearchReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gcv.services.MicroSyntenySearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MicroSyntenySearch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gcv.services.MicroSyntenySearch/Search',
            services_dot_microsyntenysearch__pb2.MicroSyntenySearchRequest.SerializeToString,
            services_dot_microsyntenysearch__pb2.MicroSyntenySearchReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
