# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genes.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='genes.proto',
  package='genes',
  syntax='proto3',
  serialized_options=b'\n\rlis.gcv.genesB\nGenesProtoP\001\242\002\002GS',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bgenes.proto\x12\x05genes\"\x1b\n\nGetRequest\x12\r\n\x05names\x18\x01 \x03(\t\"&\n\x08GetReply\x12\x1a\n\x05genes\x18\x01 \x03(\x0b\x32\x0b.genes.Gene\"d\n\x04Gene\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x66min\x18\x02 \x01(\r\x12\x0c\n\x04\x66max\x18\x03 \x01(\r\x12\x0e\n\x06strand\x18\x04 \x01(\r\x12\x0e\n\x06\x66\x61mily\x18\x05 \x01(\t\x12\x12\n\nchromosome\x18\x06 \x01(\t24\n\x05Genes\x12+\n\x03Get\x12\x11.genes.GetRequest\x1a\x0f.genes.GetReply\"\x00\x42\"\n\rlis.gcv.genesB\nGenesProtoP\x01\xa2\x02\x02GSb\x06proto3'
)




_GETREQUEST = _descriptor.Descriptor(
  name='GetRequest',
  full_name='genes.GetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='names', full_name='genes.GetRequest.names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=49,
)


_GETREPLY = _descriptor.Descriptor(
  name='GetReply',
  full_name='genes.GetReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='genes', full_name='genes.GetReply.genes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=89,
)


_GENE = _descriptor.Descriptor(
  name='Gene',
  full_name='genes.Gene',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='genes.Gene.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fmin', full_name='genes.Gene.fmin', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fmax', full_name='genes.Gene.fmax', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strand', full_name='genes.Gene.strand', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='family', full_name='genes.Gene.family', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chromosome', full_name='genes.Gene.chromosome', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=191,
)

_GETREPLY.fields_by_name['genes'].message_type = _GENE
DESCRIPTOR.message_types_by_name['GetRequest'] = _GETREQUEST
DESCRIPTOR.message_types_by_name['GetReply'] = _GETREPLY
DESCRIPTOR.message_types_by_name['Gene'] = _GENE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetRequest = _reflection.GeneratedProtocolMessageType('GetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREQUEST,
  '__module__' : 'genes_pb2'
  # @@protoc_insertion_point(class_scope:genes.GetRequest)
  })
_sym_db.RegisterMessage(GetRequest)

GetReply = _reflection.GeneratedProtocolMessageType('GetReply', (_message.Message,), {
  'DESCRIPTOR' : _GETREPLY,
  '__module__' : 'genes_pb2'
  # @@protoc_insertion_point(class_scope:genes.GetReply)
  })
_sym_db.RegisterMessage(GetReply)

Gene = _reflection.GeneratedProtocolMessageType('Gene', (_message.Message,), {
  'DESCRIPTOR' : _GENE,
  '__module__' : 'genes_pb2'
  # @@protoc_insertion_point(class_scope:genes.Gene)
  })
_sym_db.RegisterMessage(Gene)


DESCRIPTOR._options = None

_GENES = _descriptor.ServiceDescriptor(
  name='Genes',
  full_name='genes.Genes',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=193,
  serialized_end=245,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='genes.Genes.Get',
    index=0,
    containing_service=None,
    input_type=_GETREQUEST,
    output_type=_GETREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GENES)

DESCRIPTOR.services_by_name['Genes'] = _GENES

# @@protoc_insertion_point(module_scope)
