openapi: 3.0.0
info:
  title: "RESTful API for DSCensor Directed Graph"
  version: 2.0.0
servers:
  - url: /
paths:
  /genera:
    get:
      summary: Get list of all Genera
      responses:
        "200":
          $ref: "#/components/responses/GenusList"

  /genera/{genus}/species:
    get:
      summary: Get list of all species within a genus
      parameters:
        - $ref: "#/components/parameters/Genus"
      responses:
        "200":
          $ref: "#/components/responses/SpeciesList"

  /species:
    get:
      summary: Get list of all species
      responses:
        "200":
          $ref: "#/components/responses/SpeciesList"

  /genomes:
    get:
      summary: Get list of all genome_main objects
      description: |
        Returns all of the genome_main objects from the digraph.
      responses:
        "200":
          $ref: "#/components/responses/GenomeList"

  /genomes/limit/{results}:
    get:
      summary: Get at most {results} genome_main objects
      parameters:
        - $ref: "#/components/parameters/Results"
      responses:
        "200":
          $ref: "#/components/responses/GenomeList"
        "400":
          $ref: "#/components/responses/BadRequest"

  /genomes/{genus}:
    get:
      summary: Get all genome_main objects for a genus
      parameters:
        - $ref: "#/components/parameters/Genus"
      responses:
        "200":
          $ref: "#/components/responses/GenomeList"

  /genomes/{genus}/limit/{results}:
    get:
      summary: Get at most {results} genome_main objects for a genus
      parameters:
        - $ref: "#/components/parameters/Genus"
        - $ref: "#/components/parameters/Results"
      responses:
        "200":
          $ref: "#/components/responses/GenomeList"
        "400":
          $ref: "#/components/responses/BadRequest"

  /genomes/{genus}/{species}:
    get:
      summary: Get all genome_main objects for a genus and species
      parameters:
        - $ref: "#/components/parameters/Genus"
        - $ref: "#/components/parameters/Species"
      responses:
        "200":
          $ref: "#/components/responses/GenomeList"

  /genomes/{genus}/{species}/limit/{results}:
    get:
      summary: Get at most {results} genome_main objects for a genus and species
      parameters:
        - $ref: "#/components/parameters/Genus"
        - $ref: "#/components/parameters/Species"
        - $ref: "#/components/parameters/Results"
      responses:
        "200":
          $ref: "#/components/responses/GenomeList"
        "400":
          $ref: "#/components/responses/BadRequest"

  /annotations:
    get:
      summary: Get list of all gene_models_main objects
      description: |
        Returns all of the gene_models_main objects from the digraph.
      responses:
        "200":
          $ref: "#/components/responses/GeneModelsMainList"

  /annotations/limit/{results}:
    get:
      summary: Get at most {results} gene_models_main objects
      parameters:
        - $ref: "#/components/parameters/Results"
      responses:
        "200":
          $ref: "#/components/responses/GeneModelsMainList"
        "400":
          $ref: "#/components/responses/BadRequest"

  /annotations/{genus}:
    get:
      summary: Get all gene_models_main objects for a genus
      parameters:
        - $ref: "#/components/parameters/Genus"
      responses:
        "200":
          $ref: "#/components/responses/GeneModelsMainList"

  /annotations/{genus}/limit/{results}:
    get:
      summary: Get at most {results} gene_models_main objects for a genus
      parameters:
        - $ref: "#/components/parameters/Genus"
        - $ref: "#/components/parameters/Results"
      responses:
        "200":
          $ref: "#/components/responses/GeneModelsMainList"
        "400":
          $ref: "#/components/responses/BadRequest"

  /annotations/{genus}/{species}:
    get:
      summary: Get all gene_models_main objects for a genus and species
      parameters:
        - $ref: "#/components/parameters/Genus"
        - $ref: "#/components/parameters/Species"
      responses:
        "200":
          $ref: "#/components/responses/GeneModelsMainList"

  /annotations/{genus}/{species}/limit/{results}:
    get:
      summary: Get at most {results} gene_models_main objects for a genus and species
      parameters:
        - $ref: "#/components/parameters/Genus"
        - $ref: "#/components/parameters/Species"
        - $ref: "#/components/parameters/Results"
      responses:
        "200":
          $ref: "#/components/responses/GeneModelsMainList"
        "400":
          $ref: "#/components/responses/BadRequest"

  /proteins:
    get:
      summary: Get list of all protein objects
      description: |
        Returns all of the protein objects from the digraph.
      responses:
        "200":
          $ref: "#/components/responses/ProteinList"

  /proteins/limit/{results}:
    get:
      summary: Get at most {results} protein objects
      parameters:
        - $ref: "#/components/parameters/Results"
      responses:
        "200":
          $ref: "#/components/responses/ProteinList"
        "400":
          $ref: "#/components/responses/BadRequest"

  /proteins/{genus}:
    get:
      summary: Get all protein objects for a genus
      parameters:
        - $ref: "#/components/parameters/Genus"
      responses:
        "200":
          $ref: "#/components/responses/ProteinList"

  /proteins/{genus}/limit/{results}:
    get:
      summary: Get at most {results} protein objects for a genus
      parameters:
        - $ref: "#/components/parameters/Genus"
        - $ref: "#/components/parameters/Results"
      responses:
        "200":
          $ref: "#/components/responses/ProteinList"
        "400":
          $ref: "#/components/responses/BadRequest"

  /proteins/{genus}/{species}:
    get:
      summary: Get all protein objects for a genus and species
      parameters:
        - $ref: "#/components/parameters/Genus"
        - $ref: "#/components/parameters/Species"
      responses:
        "200":
          $ref: "#/components/responses/ProteinList"

  /proteins/{genus}/{species}/limit/{results}:
    get:
      summary: Get at most {results} protein objects for a genus and species
      parameters:
        - $ref: "#/components/parameters/Genus"
        - $ref: "#/components/parameters/Species"
        - $ref: "#/components/parameters/Results"
      responses:
        "200":
          $ref: "#/components/responses/ProteinList"
        "400":
          $ref: "#/components/responses/BadRequest"

  /proteins_primary:
    get:
      summary: Get list of all protein_primary objects
      description: |
        Returns all of the protein_primary objects from the digraph.
      responses:
        "200":
          $ref: "#/components/responses/ProteinPrimaryList"

  /proteins_primary/limit/{results}:
    get:
      summary: Get at most {results} protein_primary objects
      parameters:
        - $ref: "#/components/parameters/Results"
      responses:
        "200":
          $ref: "#/components/responses/ProteinPrimaryList"
        "400":
          $ref: "#/components/responses/BadRequest"

  /proteins_primary/{genus}:
    get:
      summary: Get all protein_primary objects for a genus
      parameters:
        - $ref: "#/components/parameters/Genus"
      responses:
        "200":
          $ref: "#/components/responses/ProteinPrimaryList"

  /proteins_primary/{genus}/limit/{results}:
    get:
      summary: Get at most {results} protein_primary objects for a genus
      parameters:
        - $ref: "#/components/parameters/Genus"
        - $ref: "#/components/parameters/Results"
      responses:
        "200":
          $ref: "#/components/responses/ProteinPrimaryList"
        "400":
          $ref: "#/components/responses/BadRequest"

  /proteins_primary/{genus}/{species}:
    get:
      summary: Get all protein_primary objects for a genus and species
      parameters:
        - $ref: "#/components/parameters/Genus"
        - $ref: "#/components/parameters/Species"
      responses:
        "200":
          $ref: "#/components/responses/ProteinPrimaryList"

  /proteins_primary/{genus}/{species}/limit/{results}:
    get:
      summary: Get at most {results} protein_primary objects for a genus and species
      parameters:
        - $ref: "#/components/parameters/Genus"
        - $ref: "#/components/parameters/Species"
        - $ref: "#/components/parameters/Results"
      responses:
        "200":
          $ref: "#/components/responses/ProteinPrimaryList"
        "400":
          $ref: "#/components/responses/BadRequest"

components:
  parameters:
    Genus:
      in: path
      name: genus
      required: true
      schema:
        type: string
      description: Return only objects matching this genus (case-insensitive)
    Species:
      in: path
      name: species
      required: true
      schema:
        type: string
      description: Return only objects matching this species (case-insensitive)
    Results:
      in: path
      name: results
      required: true
      schema:
        type: integer
        minimum: 1
      description: Return at most this many objects

  responses:
    GenusList:
      description: "SUCCESS"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Genus"
    SpeciesList:
      description: "SUCCESS"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Species"
    GenomeList:
      description: "SUCCESS"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Genome"
    GeneModelsMainList:
      description: "SUCCESS"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/GeneModelsMain"
    ProteinList:
      description: "SUCCESS"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Protein"
    ProteinPrimaryList:
      description: "SUCCESS"
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/ProteinPrimary"
    BadRequest:
      description: "'results' must be a positive integer"

  schemas:
    Genus:
      type: array
      items:
        type: string

    Species:
      type: array
      items:
        type: string

    Genome:
      type: object
      properties:
        metadata:
          $ref: "#/components/schemas/CoreObject"
        counts:
          $ref: "#/components/schemas/Counts"
        busco:
          $ref: "#/components/schemas/Busco"

    GeneModelsMain:
      type: object
      properties:
        metadata:
          $ref: "#/components/schemas/CoreObject"
        counts:
          $ref: "#/components/schemas/Counts"
        busco:
          $ref: "#/components/schemas/Busco"

    Protein:
      type: object
      properties:
        metadata:
          $ref: "#/components/schemas/CoreObject"
        counts:
          $ref: "#/components/schemas/Counts"
        busco:
          $ref: "#/components/schemas/Busco"

    ProteinPrimary:
      type: object
      properties:
        metadata:
          $ref: "#/components/schemas/CoreObject"
        counts:
          $ref: "#/components/schemas/Counts"
        busco:
          $ref: "#/components/schemas/Busco"

    Counts:
      type: object
      properties:
        contigs:
          type: integer
        records:
          type: integer
        N50:
          type: integer
        allbases:
          type: integer
        gapbases:
          type: integer
        gaps:
          type: integer

    CoreObject:
      type: object
      properties:
        filename:
          type: string
        filetype:
          type: string
        canonical_type:
          type: string
        url:
          type: string
        genus:
          type: string
        species:
          type: string
        origin:
          type: string
        infraspecies:
          type: string
        derived_from:
          type: array
          items:
            type: string

    Busco:
      type: object
      properties:
        complete_buscos:
          type: integer
        single_copy_buscos:
          type: integer
        duplicate_buscos:
          type: integer
        fragmented_buscos:
          type: integer
        missing_buscos:
          type: integer
        total_buscos:
          type: integer
