# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from chromosome_search.services import chromosomesearch_pb2 as services_dot_chromosomesearch__pb2


class ChromosomeSearchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/gcv.services.ChromosomeSearch/Search',
                request_serializer=services_dot_chromosomesearch__pb2.ChromosomeSearchRequest.SerializeToString,
                response_deserializer=services_dot_chromosomesearch__pb2.ChromosomeSearchReply.FromString,
                )


class ChromosomeSearchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChromosomeSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=services_dot_chromosomesearch__pb2.ChromosomeSearchRequest.FromString,
                    response_serializer=services_dot_chromosomesearch__pb2.ChromosomeSearchReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gcv.services.ChromosomeSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChromosomeSearch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gcv.services.ChromosomeSearch/Search',
            services_dot_chromosomesearch__pb2.ChromosomeSearchRequest.SerializeToString,
            services_dot_chromosomesearch__pb2.ChromosomeSearchReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
