# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/macrosyntenyblocks.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from structures import block_pb2 as structures_dot_block__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='services/macrosyntenyblocks.proto',
  package='gcv.services',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!services/macrosyntenyblocks.proto\x12\x0cgcv.services\x1a\x16structures/block.proto\"\x8a\x01\n MacroSyntenyBlocksComputeRequest\x12\x12\n\nchromosome\x18\x01 \x03(\t\x12\x0f\n\x07matched\x18\x02 \x01(\r\x12\x14\n\x0cintermediate\x18\x03 \x01(\r\x12\x11\n\x04mask\x18\x04 \x01(\rH\x00\x88\x01\x01\x12\x0f\n\x07targets\x18\x05 \x03(\tB\x07\n\x05_mask\"H\n\x1eMacroSyntenyBlocksComputeReply\x12&\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x16.gcv.structures.Blocks2\x7f\n\x12MacroSyntenyBlocks\x12i\n\x07\x43ompute\x12..gcv.services.MacroSyntenyBlocksComputeRequest\x1a,.gcv.services.MacroSyntenyBlocksComputeReply\"\x00\x62\x06proto3'
  ,
  dependencies=[structures_dot_block__pb2.DESCRIPTOR,])




_MACROSYNTENYBLOCKSCOMPUTEREQUEST = _descriptor.Descriptor(
  name='MacroSyntenyBlocksComputeRequest',
  full_name='gcv.services.MacroSyntenyBlocksComputeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chromosome', full_name='gcv.services.MacroSyntenyBlocksComputeRequest.chromosome', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='matched', full_name='gcv.services.MacroSyntenyBlocksComputeRequest.matched', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intermediate', full_name='gcv.services.MacroSyntenyBlocksComputeRequest.intermediate', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mask', full_name='gcv.services.MacroSyntenyBlocksComputeRequest.mask', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='targets', full_name='gcv.services.MacroSyntenyBlocksComputeRequest.targets', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_mask', full_name='gcv.services.MacroSyntenyBlocksComputeRequest._mask',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=76,
  serialized_end=214,
)


_MACROSYNTENYBLOCKSCOMPUTEREPLY = _descriptor.Descriptor(
  name='MacroSyntenyBlocksComputeReply',
  full_name='gcv.services.MacroSyntenyBlocksComputeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blocks', full_name='gcv.services.MacroSyntenyBlocksComputeReply.blocks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=288,
)

_MACROSYNTENYBLOCKSCOMPUTEREQUEST.oneofs_by_name['_mask'].fields.append(
  _MACROSYNTENYBLOCKSCOMPUTEREQUEST.fields_by_name['mask'])
_MACROSYNTENYBLOCKSCOMPUTEREQUEST.fields_by_name['mask'].containing_oneof = _MACROSYNTENYBLOCKSCOMPUTEREQUEST.oneofs_by_name['_mask']
_MACROSYNTENYBLOCKSCOMPUTEREPLY.fields_by_name['blocks'].message_type = structures_dot_block__pb2._BLOCKS
DESCRIPTOR.message_types_by_name['MacroSyntenyBlocksComputeRequest'] = _MACROSYNTENYBLOCKSCOMPUTEREQUEST
DESCRIPTOR.message_types_by_name['MacroSyntenyBlocksComputeReply'] = _MACROSYNTENYBLOCKSCOMPUTEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MacroSyntenyBlocksComputeRequest = _reflection.GeneratedProtocolMessageType('MacroSyntenyBlocksComputeRequest', (_message.Message,), {
  'DESCRIPTOR' : _MACROSYNTENYBLOCKSCOMPUTEREQUEST,
  '__module__' : 'services.macrosyntenyblocks_pb2'
  # @@protoc_insertion_point(class_scope:gcv.services.MacroSyntenyBlocksComputeRequest)
  })
_sym_db.RegisterMessage(MacroSyntenyBlocksComputeRequest)

MacroSyntenyBlocksComputeReply = _reflection.GeneratedProtocolMessageType('MacroSyntenyBlocksComputeReply', (_message.Message,), {
  'DESCRIPTOR' : _MACROSYNTENYBLOCKSCOMPUTEREPLY,
  '__module__' : 'services.macrosyntenyblocks_pb2'
  # @@protoc_insertion_point(class_scope:gcv.services.MacroSyntenyBlocksComputeReply)
  })
_sym_db.RegisterMessage(MacroSyntenyBlocksComputeReply)



_MACROSYNTENYBLOCKS = _descriptor.ServiceDescriptor(
  name='MacroSyntenyBlocks',
  full_name='gcv.services.MacroSyntenyBlocks',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=290,
  serialized_end=417,
  methods=[
  _descriptor.MethodDescriptor(
    name='Compute',
    full_name='gcv.services.MacroSyntenyBlocks.Compute',
    index=0,
    containing_service=None,
    input_type=_MACROSYNTENYBLOCKSCOMPUTEREQUEST,
    output_type=_MACROSYNTENYBLOCKSCOMPUTEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MACROSYNTENYBLOCKS)

DESCRIPTOR.services_by_name['MacroSyntenyBlocks'] = _MACROSYNTENYBLOCKS

# @@protoc_insertion_point(module_scope)
