# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import macrosyntenyblocks_pb2 as macrosyntenyblocks__pb2


class MacroSyntenyBlocksStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Compute = channel.unary_unary(
                '/macrosyntenyblocks.MacroSyntenyBlocks/Compute',
                request_serializer=macrosyntenyblocks__pb2.ComputeRequest.SerializeToString,
                response_deserializer=macrosyntenyblocks__pb2.ComputeReply.FromString,
                )


class MacroSyntenyBlocksServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Compute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MacroSyntenyBlocksServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Compute': grpc.unary_unary_rpc_method_handler(
                    servicer.Compute,
                    request_deserializer=macrosyntenyblocks__pb2.ComputeRequest.FromString,
                    response_serializer=macrosyntenyblocks__pb2.ComputeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'macrosyntenyblocks.MacroSyntenyBlocks', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MacroSyntenyBlocks(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Compute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/macrosyntenyblocks.MacroSyntenyBlocks/Compute',
            macrosyntenyblocks__pb2.ComputeRequest.SerializeToString,
            macrosyntenyblocks__pb2.ComputeReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
