# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: macrosyntenyblocks.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='macrosyntenyblocks.proto',
  package='macrosyntenyblocks',
  syntax='proto3',
  serialized_options=b'\n\032lis.gcv.macrosyntenyblocksB\027MacroSyntenyBlocksProtoP\001\242\002\002GS',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18macrosyntenyblocks.proto\x12\x12macrosyntenyblocks\"x\n\x0e\x43omputeRequest\x12\x12\n\nchromosome\x18\x01 \x03(\t\x12\x0f\n\x07matched\x18\x02 \x01(\r\x12\x14\n\x0cintermediate\x18\x03 \x01(\r\x12\x11\n\x04mask\x18\x04 \x01(\rH\x00\x88\x01\x01\x12\x0f\n\x07targets\x18\x05 \x03(\tB\x07\n\x05_mask\":\n\x0c\x43omputeReply\x12*\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x1a.macrosyntenyblocks.Blocks\"g\n\x06\x42locks\x12\x12\n\nchromosome\x18\x01 \x01(\t\x12\r\n\x05genus\x18\x02 \x01(\t\x12\x0f\n\x07species\x18\x03 \x01(\t\x12)\n\x06\x62locks\x18\x04 \x03(\x0b\x32\x19.macrosyntenyblocks.Block\"N\n\x05\x42lock\x12\t\n\x01i\x18\x01 \x01(\r\x12\t\n\x01j\x18\x02 \x01(\r\x12\x0c\n\x04\x66min\x18\x03 \x01(\r\x12\x0c\n\x04\x66max\x18\x04 \x01(\r\x12\x13\n\x0borientation\x18\x05 \x01(\t2g\n\x12MacroSyntenyBlocks\x12Q\n\x07\x43ompute\x12\".macrosyntenyblocks.ComputeRequest\x1a .macrosyntenyblocks.ComputeReply\"\x00\x42<\n\x1alis.gcv.macrosyntenyblocksB\x17MacroSyntenyBlocksProtoP\x01\xa2\x02\x02GSb\x06proto3'
)




_COMPUTEREQUEST = _descriptor.Descriptor(
  name='ComputeRequest',
  full_name='macrosyntenyblocks.ComputeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chromosome', full_name='macrosyntenyblocks.ComputeRequest.chromosome', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='matched', full_name='macrosyntenyblocks.ComputeRequest.matched', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intermediate', full_name='macrosyntenyblocks.ComputeRequest.intermediate', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mask', full_name='macrosyntenyblocks.ComputeRequest.mask', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='targets', full_name='macrosyntenyblocks.ComputeRequest.targets', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_mask', full_name='macrosyntenyblocks.ComputeRequest._mask',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=48,
  serialized_end=168,
)


_COMPUTEREPLY = _descriptor.Descriptor(
  name='ComputeReply',
  full_name='macrosyntenyblocks.ComputeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blocks', full_name='macrosyntenyblocks.ComputeReply.blocks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=228,
)


_BLOCKS = _descriptor.Descriptor(
  name='Blocks',
  full_name='macrosyntenyblocks.Blocks',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chromosome', full_name='macrosyntenyblocks.Blocks.chromosome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='genus', full_name='macrosyntenyblocks.Blocks.genus', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='species', full_name='macrosyntenyblocks.Blocks.species', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blocks', full_name='macrosyntenyblocks.Blocks.blocks', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=333,
)


_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='macrosyntenyblocks.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='i', full_name='macrosyntenyblocks.Block.i', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='j', full_name='macrosyntenyblocks.Block.j', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fmin', full_name='macrosyntenyblocks.Block.fmin', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fmax', full_name='macrosyntenyblocks.Block.fmax', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='macrosyntenyblocks.Block.orientation', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=413,
)

_COMPUTEREQUEST.oneofs_by_name['_mask'].fields.append(
  _COMPUTEREQUEST.fields_by_name['mask'])
_COMPUTEREQUEST.fields_by_name['mask'].containing_oneof = _COMPUTEREQUEST.oneofs_by_name['_mask']
_COMPUTEREPLY.fields_by_name['blocks'].message_type = _BLOCKS
_BLOCKS.fields_by_name['blocks'].message_type = _BLOCK
DESCRIPTOR.message_types_by_name['ComputeRequest'] = _COMPUTEREQUEST
DESCRIPTOR.message_types_by_name['ComputeReply'] = _COMPUTEREPLY
DESCRIPTOR.message_types_by_name['Blocks'] = _BLOCKS
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComputeRequest = _reflection.GeneratedProtocolMessageType('ComputeRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTEREQUEST,
  '__module__' : 'macrosyntenyblocks_pb2'
  # @@protoc_insertion_point(class_scope:macrosyntenyblocks.ComputeRequest)
  })
_sym_db.RegisterMessage(ComputeRequest)

ComputeReply = _reflection.GeneratedProtocolMessageType('ComputeReply', (_message.Message,), {
  'DESCRIPTOR' : _COMPUTEREPLY,
  '__module__' : 'macrosyntenyblocks_pb2'
  # @@protoc_insertion_point(class_scope:macrosyntenyblocks.ComputeReply)
  })
_sym_db.RegisterMessage(ComputeReply)

Blocks = _reflection.GeneratedProtocolMessageType('Blocks', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKS,
  '__module__' : 'macrosyntenyblocks_pb2'
  # @@protoc_insertion_point(class_scope:macrosyntenyblocks.Blocks)
  })
_sym_db.RegisterMessage(Blocks)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {
  'DESCRIPTOR' : _BLOCK,
  '__module__' : 'macrosyntenyblocks_pb2'
  # @@protoc_insertion_point(class_scope:macrosyntenyblocks.Block)
  })
_sym_db.RegisterMessage(Block)


DESCRIPTOR._options = None

_MACROSYNTENYBLOCKS = _descriptor.ServiceDescriptor(
  name='MacroSyntenyBlocks',
  full_name='macrosyntenyblocks.MacroSyntenyBlocks',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=415,
  serialized_end=518,
  methods=[
  _descriptor.MethodDescriptor(
    name='Compute',
    full_name='macrosyntenyblocks.MacroSyntenyBlocks.Compute',
    index=0,
    containing_service=None,
    input_type=_COMPUTEREQUEST,
    output_type=_COMPUTEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MACROSYNTENYBLOCKS)

DESCRIPTOR.services_by_name['MacroSyntenyBlocks'] = _MACROSYNTENYBLOCKS

# @@protoc_insertion_point(module_scope)
