# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: structures/chromosome.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from chromosome.structures import track_pb2 as structures_dot_track__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='structures/chromosome.proto',
  package='gcv.structures',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bstructures/chromosome.proto\x12\x0egcv.structures\x1a\x16structures/track.proto\"B\n\nChromosome\x12\x0e\n\x06length\x18\x01 \x01(\r\x12$\n\x05track\x18\x02 \x01(\x0b\x32\x15.gcv.structures.Trackb\x06proto3'
  ,
  dependencies=[structures_dot_track__pb2.DESCRIPTOR,])




_CHROMOSOME = _descriptor.Descriptor(
  name='Chromosome',
  full_name='gcv.structures.Chromosome',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='gcv.structures.Chromosome.length', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='track', full_name='gcv.structures.Chromosome.track', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=137,
)

_CHROMOSOME.fields_by_name['track'].message_type = structures_dot_track__pb2._TRACK
DESCRIPTOR.message_types_by_name['Chromosome'] = _CHROMOSOME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Chromosome = _reflection.GeneratedProtocolMessageType('Chromosome', (_message.Message,), {
  'DESCRIPTOR' : _CHROMOSOME,
  '__module__' : 'structures.chromosome_pb2'
  # @@protoc_insertion_point(class_scope:gcv.structures.Chromosome)
  })
_sym_db.RegisterMessage(Chromosome)


# @@protoc_insertion_point(module_scope)
