# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: structures/gene.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='structures/gene.proto',
  package='gcv.structures',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15structures/gene.proto\x12\x0egcv.structures\"d\n\x04Gene\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x66min\x18\x02 \x01(\r\x12\x0c\n\x04\x66max\x18\x03 \x01(\r\x12\x0e\n\x06strand\x18\x04 \x01(\x05\x12\x0e\n\x06\x66\x61mily\x18\x05 \x01(\t\x12\x12\n\nchromosome\x18\x06 \x01(\tb\x06proto3'
)




_GENE = _descriptor.Descriptor(
  name='Gene',
  full_name='gcv.structures.Gene',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gcv.structures.Gene.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fmin', full_name='gcv.structures.Gene.fmin', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fmax', full_name='gcv.structures.Gene.fmax', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strand', full_name='gcv.structures.Gene.strand', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='family', full_name='gcv.structures.Gene.family', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chromosome', full_name='gcv.structures.Gene.chromosome', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['Gene'] = _GENE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Gene = _reflection.GeneratedProtocolMessageType('Gene', (_message.Message,), {
  'DESCRIPTOR' : _GENE,
  '__module__' : 'structures.gene_pb2'
  # @@protoc_insertion_point(class_scope:gcv.structures.Gene)
  })
_sym_db.RegisterMessage(Gene)


# @@protoc_insertion_point(module_scope)
