# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from chromosome_region.services import chromosomeregion_pb2 as services_dot_chromosomeregion__pb2


class ChromosomeRegionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/gcv.services.ChromosomeRegion/Get',
                request_serializer=services_dot_chromosomeregion__pb2.ChromosomeRegionGetRequest.SerializeToString,
                response_deserializer=services_dot_chromosomeregion__pb2.ChromosomeRegionGetReply.FromString,
                )


class ChromosomeRegionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChromosomeRegionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=services_dot_chromosomeregion__pb2.ChromosomeRegionGetRequest.FromString,
                    response_serializer=services_dot_chromosomeregion__pb2.ChromosomeRegionGetReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gcv.services.ChromosomeRegion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChromosomeRegion(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gcv.services.ChromosomeRegion/Get',
            services_dot_chromosomeregion__pb2.ChromosomeRegionGetRequest.SerializeToString,
            services_dot_chromosomeregion__pb2.ChromosomeRegionGetReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
