services:
  dscensor:
    build:
      context: .
    environment:
      NODES: "/dscensor_nodes"
    ports:
      - "${PORT:-8080}:8080"
    volumes: 
      - ${DATA:-./dscensor_nodes}:/dscensor_nodes
