# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/chromosomesearch.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='services/chromosomesearch.proto',
  package='gcv.services',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fservices/chromosomesearch.proto\x12\x0cgcv.services\"(\n\x17\x43hromosomeSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\",\n\x15\x43hromosomeSearchReply\x12\x13\n\x0b\x63hromosomes\x18\x01 \x03(\t2j\n\x10\x43hromosomeSearch\x12V\n\x06Search\x12%.gcv.services.ChromosomeSearchRequest\x1a#.gcv.services.ChromosomeSearchReply\"\x00\x62\x06proto3'
)




_CHROMOSOMESEARCHREQUEST = _descriptor.Descriptor(
  name='ChromosomeSearchRequest',
  full_name='gcv.services.ChromosomeSearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='gcv.services.ChromosomeSearchRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=89,
)


_CHROMOSOMESEARCHREPLY = _descriptor.Descriptor(
  name='ChromosomeSearchReply',
  full_name='gcv.services.ChromosomeSearchReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chromosomes', full_name='gcv.services.ChromosomeSearchReply.chromosomes', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['ChromosomeSearchRequest'] = _CHROMOSOMESEARCHREQUEST
DESCRIPTOR.message_types_by_name['ChromosomeSearchReply'] = _CHROMOSOMESEARCHREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChromosomeSearchRequest = _reflection.GeneratedProtocolMessageType('ChromosomeSearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHROMOSOMESEARCHREQUEST,
  '__module__' : 'services.chromosomesearch_pb2'
  # @@protoc_insertion_point(class_scope:gcv.services.ChromosomeSearchRequest)
  })
_sym_db.RegisterMessage(ChromosomeSearchRequest)

ChromosomeSearchReply = _reflection.GeneratedProtocolMessageType('ChromosomeSearchReply', (_message.Message,), {
  'DESCRIPTOR' : _CHROMOSOMESEARCHREPLY,
  '__module__' : 'services.chromosomesearch_pb2'
  # @@protoc_insertion_point(class_scope:gcv.services.ChromosomeSearchReply)
  })
_sym_db.RegisterMessage(ChromosomeSearchReply)



_CHROMOSOMESEARCH = _descriptor.ServiceDescriptor(
  name='ChromosomeSearch',
  full_name='gcv.services.ChromosomeSearch',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=137,
  serialized_end=243,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='gcv.services.ChromosomeSearch.Search',
    index=0,
    containing_service=None,
    input_type=_CHROMOSOMESEARCHREQUEST,
    output_type=_CHROMOSOMESEARCHREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHROMOSOMESEARCH)

DESCRIPTOR.services_by_name['ChromosomeSearch'] = _CHROMOSOMESEARCH

# @@protoc_insertion_point(module_scope)
