# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: structures/microtrack.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from micro_synteny_search.structures import track_pb2 as structures_dot_track__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='structures/microtrack.proto',
  package='gcv.structures',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bstructures/microtrack.proto\x12\x0egcv.structures\x1a\x16structures/track.proto\"@\n\nMicroTrack\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x05track\x18\x02 \x01(\x0b\x32\x15.gcv.structures.Trackb\x06proto3'
  ,
  dependencies=[structures_dot_track__pb2.DESCRIPTOR,])




_MICROTRACK = _descriptor.Descriptor(
  name='MicroTrack',
  full_name='gcv.structures.MicroTrack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gcv.structures.MicroTrack.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='track', full_name='gcv.structures.MicroTrack.track', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=135,
)

_MICROTRACK.fields_by_name['track'].message_type = structures_dot_track__pb2._TRACK
DESCRIPTOR.message_types_by_name['MicroTrack'] = _MICROTRACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MicroTrack = _reflection.GeneratedProtocolMessageType('MicroTrack', (_message.Message,), {
  'DESCRIPTOR' : _MICROTRACK,
  '__module__' : 'structures.microtrack_pb2'
  # @@protoc_insertion_point(class_scope:gcv.structures.MicroTrack)
  })
_sym_db.RegisterMessage(MicroTrack)


# @@protoc_insertion_point(module_scope)
